Add upstream coverage
Add coveralls.io coverage for github code as well as the badge in the
README.rst file.

Need to pin coverage to version 3.7.1 to avoid exception in coveralls:
ImportError: cannot import name coverage