Return descriptive error message on AttributeError
Attribute errors of base GCS class were not returning any message when
raising AttributeError.

This patch makes GCS base class raise AttributeError with a meaningful
message.  Same format as Python's default message is used.

Example:

  AttributeError: 'Project' object has no attribute 'fake'